"""
Django settings for maxibidder project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os  #Agrego esta linea -****************************************************************************

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5ira^p9v_t0eqr3y$dckm!znrhh20ajg8h$mhg@8azwn7-kw%p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  #ojo cuando este en desarrollo ojo con la linea de abajo allowed_host

ALLOWED_HOSTS = []

LOGIN_URL = 'login'  # Usa el nombre de la URL de login en gestioncar/urls.py
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'gestioncar',
]



# Configuración para los mensajes  AGREGUE ESTO --------------------------------------
from django.contrib import messages
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.DEBUG: 'alert-dark',
    message_constants.INFO: 'alert-info',
    message_constants.SUCCESS: 'alert-success',
    message_constants.WARNING: 'alert-warning',
    message_constants.ERROR: 'alert-danger',  # Clase para mensajes de error
    messages.ERROR: 'alert-danger',  # Clase para errores
}
#hasta aca manejo de mensajes--------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'maxibidder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [],
        'DIRS': [BASE_DIR / 'templates'],  # Agrega el directorio templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'maxibidder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bdcarmaxibidder',
        'USER': 'postgres',
        'PASSWORD': '0Zon0+_+',
        'HOST': '127.0.0.1',
        'DATABASE_PORT': '5432'


        #'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Configuración para archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'gestioncar/static')]

# Configuración para archivos multimedia
MEDIA_URL = '/media/'  # URL base para servir archivos multimedia
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Ruta en el sistema de archivos donde se almacenarán los archivos multimedia


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración para manejar errores 403 (Forbidden)   -------AGREGE ESTO  EL 13/02/2025 DESDE ACA EN ADELANTE
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']  # Solo necesario en producción
CSRF_FAILURE_VIEW = 'gestioncar.views.csrf_failure'  # Vista personalizada para CSRF
HANDLER403 = 'gestioncar.views.handler403'  # Vista personalizada para acceso denegado
# Configuración de seguridad adicional (opcional)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

#CONFIGURACIONES ADICIONALES REGISTRO POR EMAIL 15-02-2025
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Servidor SMTP de Gmail (ejemplo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Muestra emails en consola
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587 # Puerto para TLS
EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'hogartv54@gmail.com'
#EMAIL_HOST_PASSWORD = '05112012'
#DEFAULT_FROM_EMAIL = 'hogartv54@gmail.com'  # Añade esta línea
EMAIL_HOST_USER = os.getenv('GMAIL_USER', 'hogartv54@gmail.com')  # Usa variables de entorno
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD')  # Ej: 'xlkd rqwo qzxy abcd'

AUTHENTICATION_BACKENDS = [
    'gestioncar.auth_backends.EmailAuthBackend',  # Primero nuestro backend
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto
]