# Generated by Django 4.2 on 2025-01-27 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=7, unique=True)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'Continuously Variable Transmission (CVT)'), ('DSG/DGT', 'Dual Clutch (DSG or DGT)'), ('AMT', 'Manual Automated (AMT)'), ('Sequential Manual', 'Manual Sequential'), ('EVT', 'Electronic Variable Transmission (EVT)'), ('Hydraulic', 'Hydraulic')], max_length=30, verbose_name='transmission')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback')], max_length=30, verbose_name='vehicle_type')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('foto_principal', models.ImageField(null=True, upload_to='main_picture')),
                ('date_add', models.DateField(default=None, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_model', to='gestioncar.carmodel')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_make', to='gestioncar.carmake')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='video_cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_carro', to='gestioncar.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='fot_cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_car', to='gestioncar.vehicle')),
            ],
        ),
    ]
