# Generated by Django 4.2 on 2025-01-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncar', '0002_vehicle_video_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='car',
        ),
        migrations.RemoveField(
            model_name='video',
            name='car',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='details',
            field=models.TextField(blank=True, help_text='Enter additional details about the vehicle', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fotos',
            field=models.ManyToManyField(blank=True, related_name='photos_car', to='gestioncar.photo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='links',
            field=models.TextField(blank=True, help_text='Enter one or more URLs, separated by line breaks', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='title_condition',
            field=models.CharField(choices=[('Clean', 'Clean'), ('Rebuilt', 'Rebuilt'), ('Salvage', 'Salvage')], max_length=10, null=True, verbose_name='Title Condition'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos_carro', to='gestioncar.video'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='img_car_vid/ima_car/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='foto_principal',
            field=models.ImageField(null=True, upload_to='img_car_vid/ima_car/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'Continuously Variable Transmission (CVT)'), ('DSG/DGT', 'Dual Clutch (DSG or DGT)'), ('AMT', 'Manual Automated (AMT)'), ('Sequential Manual', 'Manual Sequential'), ('EVT', 'Electronic Variable Transmission (EVT)'), ('Hydraulic', 'Hydraulic')], max_length=30, verbose_name='Transmission'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback')], max_length=30, verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='img_car_vid/ima_vid/'),
        ),
    ]
