# Generated by Django 4.2 on 2025-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncar', '0003_remove_photo_car_remove_video_car_vehicle_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('CVT', 'Continuously Variable Transmission (CVT)'), ('DSG/DGT', 'Dual Clutch (DSG or DGT)'), ('AMT', 'Manual Automated (AMT)'), ('Sequential Manual', 'Manual Sequential'), ('EVT', 'Electronic Variable Transmission (EVT)'), ('Hydraulic', 'Hydraulic')], max_length=30, verbose_name='transmission'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback')], max_length=30, verbose_name='vehicle_type'),
        ),
    ]
