# Generated by Django 4.2 on 2025-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncar', '0005_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Mostrar Descripción'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='show_slider',
            field=models.BooleanField(default=True, verbose_name='Mostrar Slider'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Mostrar Título'),
        ),
    ]
