# Generated by Django 4.2 on 2025-02-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncar', '0008_remove_profile_id_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_catalog',
            field=models.BooleanField(default=True, verbose_name='Receive monthly catalog'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_newsletter',
            field=models.BooleanField(default=True, verbose_name='Receive newsletter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='Receive notifications'),
        ),
    ]
